### PR TITLE
Add breaklines snippet

### PR DESCRIPTION
**Pull request by gabrielpconceicao**
Add's ```breaklines``` snippet.

### CODE REVIEW

**Comment by cusspvz** [comment]
@gabrielpconceicao could you please add changes on `CHANGELOG.md`?

**Comment by gabrielpconceicao** [comment]
Done.

**Comment by gabrielpconceicao** [comment]
Done.

**Comment by gabrielpconceicao** [comment]
Done.

**Comment by cusspvz** [comment]
I would tag a new release it asap.

**Pull request merged**
